default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: agb

development:
  <<: *default
  host: localhost
  user: tiagopog
  password: 123

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  host: 
  password: 
