default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: agb

localhost: &localhost
  host: localhost
  user: tiagopog
  password: 123

development:
  <<: *default
  <<: *localhost

test:
  <<: *default
  <<: *localhost
  database: agb_test

production:
  <<: *default
  host: 
  password: 
